  hl_override = {{
    St_NormalMode = {{ bg = "{color3}" }},
    St_NormalModeSep = {{ fg = "{color3}", bg = "{background}" }},
    St_InsertMode = {{ bg = "{color6}" }},
    St_InsertModeSep = {{ fg = "{color6}", bg = "{background}" }},
    St_VisualMode = {{ bg = "{color1}" }},
    St_VisualModeSep = {{ fg = "{color1}", bg = "{background}" }},
    St_CommandMode = {{ bg = "{color2}" }},
    St_CommandModeSep = {{ fg = "{color2}", bg = "{background}" }},
    St_TerminalMode = {{ bg = "{color4}" }},
    St_TerminalModeSep = {{ fg = "{color4}", bg = "{background}" }},
    St_NTerminalMode = {{ bg = "{color4}" }},
    St_NTerminalModeSep = {{ fg = "{color4}", bg = "{background}" }},
    St_EmptySpace = {{ fg = "{color3}", bg = "{background}" }},
    St_file = {{ fg = "{background}", bg = "{color8}" }},
    St_file_sep = {{ fg = "{color8}" }},
    St_pos_icon = {{ fg = "{background}", bg = "{color3}" }},
    St_pos_sep = {{ fg = "{color3}", bg = "none" }},
    St_pos_text = {{ fg = "{background}", bg = "{color8}" }},
    St_Lsp = {{ fg = "{color3}" }},
    St_LspMsg = {{ fg = "{color3}" }},
    TbTabOn = {{ fg = "{color0}", bg = "{color3}" }},
    TbTabOff = {{ fg = "{color0}", bg = "{color8}" }},
  }},
  hl_add = {{
    St_Lint = {{ fg = "{color2}", bg = "none" }},
    NotifyINFOIcon = {{ fg = "green" }},
    NotifyINFOTitle = {{ fg = "green" }},
    NotifyINFOBorder = {{ fg = "grey_fg" }},
    NotifyERRORIcon = {{ fg = "red" }},
    NotifyERRORTitle = {{ fg = "red" }},
    NotifyERRORBorder = {{ fg = "grey_fg" }},
    NotifyWARNIcon = {{ fg = "yellow" }},
    NotifyWARNTitle = {{ fg = "yellow" }},
    NotifyWARNBorder = {{ fg = "grey_fg" }},
    TodoError = {{ fg = "red" }},
    TodoWarn = {{ fg = "red" }},
    TodoInfo = {{ fg = "yellow" }},
    TodoHint = {{ fg = "green" }},
    TodoTest = {{ fg = "cyan" }},
    TodoDefault = {{ fg = "grey_fg" }},
  }},
