; ____       _       _
;|  _ \ ___ | |_   _| |__   __ _ _ __
;| |_) / _ \| | | | | '_ \ / _` | '__|  z0mbi3
;|  __/ (_) | | |_| | |_) | (_| | |     https://github.com/gh0stzk/dotfiles
;|_|   \___/|_|\__, |_.__/ \__,_|_|     z0mbi3.zk@protonmail.com
;               |___/

[global/wm]

margin-bottom = 0
margin-top = 0

include-file = ../../src/config/system.ini
include-file = modules.ini

[color]
bg = #181825
fg = #cdd6f4

red = #f38ba8
pink = #f5c2e7
purple = #cba6f7
blue = #89b4fa
cyan = #94e2d5
green = #a6e3a1
yellow = #f9e2af
lavander = #b4befe
peach = #f2d5cf
amber = #ff77a0
orange = #fab387
brown = #f2cdcd
grey = #73739c
indigo = #9399b2
blue-gray = #383857

[bar/dani]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = true

width = 100%
height = 55

offset-x = 0
offset-y = 0

background = ${color.bg}
foreground = ${color.fg}

radius = 0

line-size = 2
line-color = ${color.blue}

border = 0
border-color = ${color.pink}

padding = 2

module-margin-left = 0
module-margin-right = 0

; NOTE: The -font property is a 1-based index of available fonts (which means that *-font = 1 will use font-0).
; Text
font-0 = "Bebas Neue:style=Regular:size=13;4"
# Date, BSP occupied
font-1 = "Bebas Neue:style=Bold:size=14;4"
# BSP focused
font-7 = "Bebas Neue:style=Bold:size=18;4"
; Icons
# Bluetooth
font-2 = "Symbols Nerd Font Mono:size=14;4"
# Music, Power, Bright
font-3 = "Symbols Nerd Font Mono:size=16;4"
# Tray, Keyboard, Memory, CPU, Disk, Net, Vol
font-4 = "Symbols Nerd Font Mono:size=18;4"
# Battery, User
font-5 = "Symbols Nerd Font Mono:size=20;4"
# OS icon
font-6 = "Symbols Nerd Font Mono:size=22;4"
;dpi = 96

;Modules availables but not active:
;	 updates weather mpd_control
modules-left = launcher battery network cpu_bar memory_bar filesystem
modules-center = bspwm
modules-right = tray sep bluetooth mplayer sep xkeyboard pulseaudio brightness date power usercard

separator = "  "
dim-value = 1.0

;;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll =

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
