# active, inactive, fullscreen
windowrule = opacity 1 override 1 override 1 override, match:class ^(.*)$
windowrule = opacity 0.8 override 0.9 override 1 override, match:class firefox, match:title ^Mozilla Firefox$
windowrule = opacity 0.9 override 0.95 override 1 override, match:class org.pwmt.zathura

windowrule {
    name = desktops
    float = true
    size = 1080 620
    match:class = org.(kde.gwenview|fkoehler.KTailctl|telegram.desktop|pulseaudio.pavucontrol|qbittorrent.qBittorrent|rncbc.qpwgraph|keepassxc.KeePassXC)
}

windowrule {
    name = xdg-desktop-portal-gtk
    float = true
    size = 720 480
    match:class = xdg-desktop-portal-gtk
}

windowrule {
  name = qbittorrent
  size = 540 360 
  center = true
  match:class  = org.qbittorrent.qBittorrent
  match:title = ^Remove.*$
}
windowrule {
  name = keepass
  size = 540 360 
  center = true
  match:class  = org.keepassxc.KeePassXC 
  match:title = ^Generate Password$
}

windowrule = opacity 0.9 override 0.95 override 1 override, match:class electron, match:title .*Obsidian.*$
windowrule {
    name = obsidian
    opacity = 0.9 override 0.95 override 1 override,
    workspace = 6
    match:class = obsidian
    match:title = .*Obsidian.*$
}

windowrule {
    name = discord
    workspace = 5
    match:class = discord
}

windowrule = workspace 5, match:class anki
windowrule {
    name = anki
    center = true
    size = 620 620
    match:class = anki
    match:title = ^(Options|Import).*$
}

windowrule = center true, float true, match:class mpv
windowrule {
    name = mpv-video
    size = 1080 620
    match:class = mpv
    match:title = .*\.(mkv|mp4|m4v|wmv|avi|mov)$
}
windowrule {
    name = mpv-audio
    size = 480 480
    match:class = mpv
    match:title = .*\.(m4a|mp3|aac)$
}

windowrule = float false, match:class ^(kitty)$, match:title ^(kitty)$
windowrule = no_blur false, match:class .*Term, no_focus false
windowrule = no_blur false, match:class kitty, no_focus false
windowrule = no_blur false, match:class alacritty, no_focus false
windowrule = no_blur true, match:focus false
windowrule = float true ,match:class lmms, match:title Settings
windowrule = size 640 570 ,match:class lmms, match:title Settings
windowrule = float true, match:class FloaTerm
windowrule = size 720 480 ,match:class FloaTerm, match:title FloaTerm
windowrule = size 740 480 ,match:class FloaTerm, match:title ExecTerm
windowrule = size 920 540 ,match:class FloaTerm, match:title MusicTerm
windowrule = size 720 480 ,match:class FloaTerm, match:title SoundTerm
windowrule = size 860 215 ,match:class FloaTerm, match:title DiskTerm
windowrule = size 860 600 ,match:class FloaTerm, match:title FetchTerm
windowrule = size 1080 620 ,match:class FloaTerm, match:title TopTerm
windowrule = size 1080 620 ,match:class FloaTerm, match:title K9Term
windowrule = size 1080 620 ,match:class FloaTerm, match:title TranTerm
windowrule = workspace 3 ,match:class FloaTerm, match:title FileTerm
windowrule = size 1080 620 ,match:class FloaTerm, match:title FileTerm
windowrule = workspace 2, match:class InitTerm
# windowrule = pseudo, match:class nvScratchTerm

# bye bye https://github.com/zakk4223/hyprWorkspaceLayouts
workspace = 2, layout:master # for InitTerm
workspace = 6, layout:master # for Obsidian

layerrule = dim_around rofi

windowrule {
   name = cava
   match:class = FloaTerm
   match:title = CavaTerm
   border_size = 0
   size = 920 480
}

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
    name = suppress-maximize-events
    suppress_event = maximize
    match:class = .*
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags
    match:fullscreen = false
    match:xwayland = true
    match:float = true
    match:pin = false
    match:class = ^$
    match:title = ^$
    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}
