#!/usr/bin/env bash
# aerc filter which runs w3m using socksify (from the dante package) to prevent
# any phoning home by rendered emails
export SOCKS_SERVER="127.0.0.1:1"
exec socksify w3m -I UTF-8 -T text/html -o display_link_number=1
