#!/usr/bin/env bash

KITTY_SOCKET="unix:$XDG_RUNTIME_DIR/init-term-kitty.sock"
kitty @ --to "$KITTY_SOCKET" "set-tab-title" "Tmux"
sleep 1

# Trigger keypresses in the pane
tmux send-keys -t init:1 'ydotool key 97:1 57:1 97:0 57:0' Enter
tmux send-keys -t init:1 'ydotool key 97:1 19:1 97:0 19:0' Enter

# Reload tmux config
tmux source-file ~/.config/tmux/tmux.conf

# Final shell
exec zsh
