#!/usr/bin/env bash

options=(
    "󰍁"
    ""
    "󰗽"
    "󰜉"
    "󰐥"
)

rofi_cmd() {
	rofi -dmenu \
		-p "Goodbye ${USER}" \
		-mesg "Uptime: $(uptime -p | sed -e 's/up //g')" \
		-no-click-to-exit \
		-theme "$HOME"/.config/rofi/PowerMenu.rasi
}

chosen=$(printf "%s\n" "${options[@]}" | rofi_cmd)

case $chosen in
    "󰐥")
        systemctl poweroff
        ;;
    "󰜉")
        systemctl reboot
        ;;
    "󰍁")
        hyprlock
        ;;
    "")
        ~/.config/waybar/scripts/volume-control.sh -o m
        ~/.config/dots/scripts/MediaControl --stop
        systemctl suspend
        ;;
    "󰗽")
        hyprctl dispatch exit
        ;;
esac
