#!/usr/bin/env bash
#  ████████╗███████╗██████╗ ███╗   ███╗██╗███╗   ██╗ █████╗ ██╗
#  ╚══██╔══╝██╔════╝██╔══██╗████╗ ████║██║████╗  ██║██╔══██╗██║
#     ██║   █████╗  ██████╔╝██╔████╔██║██║██╔██╗ ██║███████║██║
#     ██║   ██╔══╝  ██╔══██╗██║╚██╔╝██║██║██║╚██╗██║██╔══██║██║
#     ██║   ███████╗██║  ██║██║ ╚═╝ ██║██║██║ ╚████║██║  ██║███████╗
#     ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝
#   Script to open with selected terminal
#   Author: z0mbi3
#   url: https://github.com/gh0stzk/dotfiles

CFG_TERM="$HOME/.config/dots/.term"
DEFAULT_TERM="kitty"
ROFI_THEME="$HOME/.config/rofi/TermSelector.rasi"

# Creating config file if not exists.
[ ! -f "$CFG_TERM" ] && echo "$DEFAULT_TERM" >"$CFG_TERM"

# Main var (with optional override)
if [[ "$1" == "--override-term" && -n "$2" ]]; then
  MY_TERM="${2,,}"  # Convert to lowercase
  shift 2
else
  MY_TERM=$(<"$CFG_TERM")
fi

# Function to choose the terminal using rofi
choose_terminal() {
  local options=("Alacritty" "Kitty")
  local current_term=$(tr '[:upper:]' '[:lower:]' <"$CFG_TERM")
  local selected_index=$(printf '%s\n' "${options[@],,}" | awk -v cur="$current_term" '$0==cur {print NR-1; exit}')
  local chosen
  chosen=$(printf '%s\n' "${options[@]}" | rofi -theme "$ROFI_THEME" -mesg "[ Your current terminal is $MY_TERM ]" -dmenu -selected-row "$selected_index")
  [[ -n "$chosen" ]] && echo "${chosen,,}" >"$CFG_TERM"
}

# Terminal selector
[ "$1" = "--selecterm" ] && choose_terminal

# Launch the terminal with appropriate options
case $MY_TERM in
  "alacritty")
    case $1 in
      "--terminal")
        alacritty
        ;;
      "--floating")
        alacritty --class FloaTerm,FloaTerm --title=FloaTerm
        ;;
      "--update")
        alacritty --hold --class FloaTerm,FloaTerm --title=FloaTerm -e Updates --update-system
        ;;
      "--checkupdates")
        alacritty --hold --class FloaTerm,FloaTerm --title=FloaTerm -e Updates --print-updates
        ;;
      "--top")
        alacritty --class FloaTerm,TopTerm --title=TopTerm -e zsh -ic 'btop'
        ;;
      "--termscp")
	alacritty --class FloaTerm,TopTerm --title=TopTerm -e termscp
        ;;
      "--disk")
	alacritty --class FloaTerm,DiskTerm --title=DiskTerm \
		-e zsh -ic "~/.local/bin/disk; read -k"
        ;;
      "--k9s")
        alacritty --class FloaTerm,K9Term --title=K9Term -o font.size="10" \
	       	-e sh -ic "env KUBE_EDITOR=~/.local/bin/vim TERM=xterm-256color KUBECACHEDIR=$HOME/.cache/kube k9s"
        ;;
      "--lazydocker")
        alacritty --class FloaTerm,K9Term --title=K9Term -o font.size="10" \
	       	-e sh -ic "export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock && lazydocker"
        ;;
      "--shadow")
        alacritty --class ShadowTerm -o window.opacity="0.4"
        ;;
      "--nvim")
        alacritty -e nvim -c Nvdash
        ;;
      "--soundmixer")
        alacritty --class FloaTerm,SoundTerm --title=SoundTerm -e pulsemixer
        ;;
      "--music")
        alacritty --class FloaTerm,MusicTerm --title=MusicTerm \
		-e zsh -ic ~/.config/dots/scripts/Music
        ;;
      "--fetch")
        alacritty --class FloaTerm,FetchTerm --title=FetchTerm \
        	-o font.size="10" -e zsh -c 'fastfetch; read -k'
        ;;
    esac
    ;;
  "kitty")
    case $1 in
      "--terminal")
	kitty --config ~/.config/kitty/kitty-show.conf
        ;;
      "--init")
        tmux kill-server 2>/dev/null
        KITTY_SOCKET="unix:$XDG_RUNTIME_DIR/init-term-kitty.sock"
        # Launch Kitty + tmux InitTerminal in background
        kitty --class=InitTerm \
              --watcher tab_focus.py \
	      --listen-on "$KITTY_SOCKET" \
              --config ~/.config/kitty/kitty-hidden.conf \
              -e tmux new -s init &
	kitty @ --to "$KITTY_SOCKET" "set-tab-title" "Tmux"
        ;;
      "--floating")
        kitty --name=FloaTerm --title=FloaTerm --class=FloaTerm --config ~/.config/kitty/kitty-hidden.conf
        ;;
      "--update")
        kitty --hold --class=FloaTerm -e Updates --update-system
        ;;
      "--checkupdates")
        kitty --hold --class=Updating -e Updates --print-updates
        ;;
      "--top")
        kitty --name=TopTerm --title=TopTerm --class=FloaTerm \
		--config ~/.config/kitty/kitty-hidden.conf -e zsh -ic 'btop'
        ;;
      "--k9s")
        kitty --name=TopTerm --class=FloaTerm --config ~/.config/kitty/kitty-hidden.conf -e k9s
        ;;
      "--shadow")
        kitty --class=ShadowTerm --config ~/.config/kitty/kitty-hidden.conf -o background_opacity="0.4"
        ;;
      "--termscp")
        kitty --name=TopTerm --class=FileTerm --config ~/.config/kitty/kitty-hidden.conf -e termscp
        ;;
      "--yazi")
        kitty --config ~/.config/kitty/kitty-hidden.conf -e \
          sh -c "export EDITOR=~/.local/bin/vim && yazi ~"
        ;;
      "--yazi-tmux")
        kitty --name=FileTerm --title=FileTerm --class=FloaTerm \
          --config ~/.config/kitty/kitty-hidden.conf \
	  --override window_padding_width="4" \
          -e tmux new -s yazi -c "$HOME"  ~/.config/dots/scripts/InitYazi
        ;;
      "--yazi-tmux-last")
        kitty --name=FileTerm --title=FileTerm --class=FloaTerm \
          --config ~/.config/kitty/kitty-hidden.conf \
	  --override window_padding_width="4" \
          -e tmux new -s yazi -c "$HOME" ~/.config/dots/scripts/InitYazi --last
        ;;
      "--yazi-tmux-project")
        kitty --name=FileTerm --title=FileTerm --class=FloaTerm \
          --config ~/.config/kitty/kitty-hidden.conf \
	  --override window_padding_width="4" \
          -e tmux new -s yazi -c "$HOME" ~/.config/dots/scripts/InitYazi --project $2
        ;;
      "--nvim")
        kitty -e nvim -c Nvdash
        ;;
      "--soundmixer")
        kitty --name=SoundTerm --title=SoundTerm --class=FloaTerm -e pulsemixer
        ;;
      "--music")
        alacritty --class FloaTerm,CavaTerm --title=CavaTerm \
		-o window.opacity="0.01" -e cava &
	PINNED_PID=$!
	kitty --name MusicTerm --title MusicTerm --class FloaTerm \
	      --override font_size=10 \
	      --config ~/.config/kitty/kitty-hidden.conf \
	      -e ~/.config/dots/scripts/Music &
	MUSIC_PID=$!
	hyprctl dispatch focuswindow title:MusicTerm
	wait $MUSIC_PID
	kill $PINNED_PID 2>/dev/null
        ;;
      "--fetch")
        kitty --name=FetchTerm --title=FetchTerm --class=FloaTerm \
		--config ~/.config/kitty/kitty-hidden.conf -e zsh -c 'fastfetch; read -k'
        ;;
    esac
    ;;
  "wezterm")
    case $1 in
      "--terminal")
        wezterm start --class wezterm 
        ;;
      "--files-term")
        wezterm start --class wezterm -e zellij -s yazi -n yazi
        ;;
    esac
    ;;
esac
