# pkgs/niflveil.nix
{ pkgs, ... }:
let
  cargoLock = pkgs.writeText "Cargo.lock" ''
    # This file is automatically @generated by Cargo.
    # It is not intended for manual editing.
    version = 4

    [[package]]
    name = "niflveil"
    version = "0.1.0"
  '';
in
pkgs.rustPlatform.buildRustPackage {
  pname = "niflveil";
  version = "git-40d57fc";
  src = pkgs.fetchFromGitHub {
    owner = "mauitron";
    repo = "niflveil";
    rev = "54208d5b054b1a09e6c491159ac784fdb0f54703";
    hash = "sha256-oE0gKk2IMKiipiOgPhAjIElzL5QjSO/AhUXXGpcLtQ0=";
  };
  nativeBuildInputs = [ pkgs.gcc ];
  sourceRoot = "source/niflveil";
  # https://github.com/NixOS/nixpkgs/blob/4fc53b59aecbc25c0e173163d60155f8fca14bfd/doc/languages-frameworks/rust.section.md#building-a-crate-with-an-absent-or-out-of-date-cargolock-file
  # https://discourse.nixos.org/t/build-a-pckg-of-a-rust-app-without-cargo-lock/46957/3
  cargoLock = {
    lockFile = cargoLock;
  };
  postPatch = ''
    substituteInPlace src/main.rs \
      --replace-fail \
        'println!("{{\"text\":\"󰘸\",\"class\":\"empty\",\"tooltip\":\"No minimized windows\"}}");' \
        'println!("{{\"text\":\" \",\"class\":\"empty\",\"tooltip\":\"No minimized windows\"}}");'
    ln -s ${cargoLock} Cargo.lock
  '';
}
